name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
            autoconf automake libtool libtool-bin pkg-config build-essential g++ \
            zlib1g-dev libncurses5-dev libffi-dev ffmpeg

      - name: Install Apache ANT
        run: sudo apt-get install -y ant

      - name: Install buildozer and Cython
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Pre-accept Android SDK licenses for buildozer
        run: |
          export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
          mkdir -p $ANDROID_SDK_ROOT/licenses
          echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55\n84831b9409646a918e30573bab4c9c91346d8abd" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
          echo -e "d56f2edc556faefc5f4e8d94a2029831fae4c4a3" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license

      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      - name: Build APK (with retry)
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 60
          max_attempts: 3
          command: buildozer android debug

      - name: List root directory
        run: ls -l

      - name: List bin directory
        run: ls -l bin || echo "bin directory not found"

      - name: Print buildozer log (if exists)
        run: |
          BUILD_LOG_PATH=$(find .buildozer -name log.txt | head -n 1)
          if [ -f "$BUILD_LOG_PATH" ]; then
            cat "$BUILD_LOG_PATH"
          else
            echo "No buildozer log found"
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
