name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk libstdc++6

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Check project structure and buildozer.spec
        run: |
          ls -al
          if [ ! -f buildozer.spec ]; then
            echo "buildozer.spec not found in root. Aborting."
            exit 1
          fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
