name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies (retry)
        run: |
          for i in 1 2 3; do
            sudo apt-get update && sudo apt-get install -y \
              python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
              autoconf automake libtool libtool-bin pkg-config build-essential g++ \
              zlib1g-dev libncurses5-dev libffi-dev ffmpeg adb && break
            echo "Install system dependencies failed, retrying ($i/3)..."
            sleep 10
          done
      - name: Install Apache ANT (retry)
        run: |
          for i in 1 2 3; do
            sudo apt-get install -y ant && break
            echo "Install ant failed, retrying ($i/3)..."
            sleep 10
          done
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Set Android tool environment variables
        run: |
          echo "ANDROID_ANT_HOME=/usr/share/ant" >> $GITHUB_ENV
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
      - name: Debug ant and Java
        run: |
          which ant
          ant -version
          which javac
          javac -version
      - name: Install buildozer and Cython (retry)
        run: |
          for i in 1 2 3; do
            python -m pip install --upgrade pip && \
            pip install cython==0.29.36 && \
            pip install buildozer && break
            echo "Install buildozer and cython failed, retrying ($i/3)..."
            sleep 10
          done
      - name: Install project dependencies (retry)
        run: |
          for i in 1 2 3; do
            pip install -r requirements.txt && break
            echo "Install requirements.txt failed, retrying ($i/3)..."
            sleep 10
          done
      - name: Build APK
        run: |
          for i in 1 2 3; do
            buildozer android debug --accept-android-licenses && break
            echo "Buildozer build failed, retrying ($i/3)..."
            sleep 10
          done
      - name: Debug - List all APK files
        run: |
          echo "Searching for APK files..."
          find . -name "*.apk" -print
          echo "APK search complete"
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: '**/*.apk'
