name: Build Kivy APK (Docker)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Disable BuildKit
        run: |
          echo "DOCKER_BUILDKIT=0" | sudo tee -a /etc/environment
          echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV

      - name: Docker pull Buildozer
        run: docker pull kivy/buildozer

      - name: Build APK using Buildozer Docker
        run: |
          docker run --rm -v $PWD:/home/user/app -w /home/user/app kivy/buildozer buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
