name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk libstdc++6

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      # 触发 Buildozer 自动安装 Android SDK
      - name: Trigger Buildozer to install SDK
        run: buildozer android clean || true

      # 自动接受 Android SDK 许可，并强制安装 build-tools
      - name: Accept licenses and install build-tools
        run: |
          set -e
          SDKMAN="$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager"
          SDKROOT="$HOME/.buildozer/android/platform/android-sdk"
          if [ -x "$SDKMAN" ]; then
            yes | $SDKMAN --licenses --sdk_root=$SDKROOT
            yes | $SDKMAN --licenses
            yes | $SDKMAN "build-tools;36.0.0" --sdk_root=$SDKROOT
            yes | $SDKMAN "platforms;android-33" --sdk_root=$SDKROOT
          else
            echo "sdkmanager not found! Buildozer may have failed to install SDK."
            exit 1
          fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
