name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
            autoconf automake libtool libtool-bin pkg-config build-essential g++ \
            zlib1g-dev libncurses5-dev libffi-dev ffmpeg

      - name: Install Apache ANT
        run: sudo apt-get install -y ant

      - name: Install buildozer and Cython
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      - name: Build APK
        run: |
          buildozer android debug

      - name: List root directory
        run: ls -l

      - name: List bin directory
        run: ls -l bin || echo "bin directory not found"

      - name: Print buildozer log (if exists)
        run: cat .buildozer/android/platform/build-arm64-v8a/build/outputs/log.txt || echo "No buildozer log found"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
