name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk libstdc++6

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Ensure buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "buildozer.spec not found in root. Aborting."
            exit 1
          fi

      # 构建前先触发 SDK 下载
      - name: Trigger SDK install (may fail, just to download SDK)
        run: buildozer android debug || true

      # 自动接受 SDK 许可并安装 build-tools, 兼容各种路径
      - name: Accept licenses and install build-tools
        run: |
          set -e
          SDKROOT="$HOME/.buildozer/android/platform/android-sdk"
          SDKMAN=$(find $SDKROOT -type f -name sdkmanager | head -n 1 || true)
          echo "sdkmanager path: $SDKMAN"
          if [ ! -x "$SDKMAN" ]; then
            echo "sdkmanager not found! Here are possible locations:"
            find $SDKROOT -type f -name sdkmanager || true
            exit 1
          fi
          yes | $SDKMAN --licenses --sdk_root=$SDKROOT
          yes | $SDKMAN "build-tools;36.0.0" --sdk_root=$SDKROOT
          yes | $SDKMAN "platforms;android-33" --sdk_root=$SDKROOT

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
