name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk libstdc++6

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Ensure buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            echo "buildozer.spec not found in root. Aborting."
            exit 1
          fi

      - name: Cache .buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-cache-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-cache-${{ runner.os }}

      # 先触发SDK安装，生成SDK结构
      - name: Trigger initial SDK install
        run: buildozer android clean || true

      # 自动接受NDK/SDK所有许可（多次保险）
      - name: Accept Android SDK licenses (all locations)
        run: |
          set -e
          SDKMAN="$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager"
          SDKROOT="$HOME/.buildozer/android/platform/android-sdk"
          if [ -x "$SDKMAN" ]; then
            yes | $SDKMAN --licenses --sdk_root=$SDKROOT
            yes | $SDKMAN --licenses      # legacy
          fi

      # 自动安装build-tools及常用平台
      - name: Install required Android build-tools and platforms
        run: |
          set -e
          SDKMAN="$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager"
          SDKROOT="$HOME/.buildozer/android/platform/android-sdk"
          if [ -x "$SDKMAN" ]; then
            yes | $SDKMAN "build-tools;36.0.0" --sdk_root=$SDKROOT
            yes | $SDKMAN "platforms;android-33" --sdk_root=$SDKROOT
          fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
